package:
  name: sherpa
  version: "0.6"

source:
  path: "{{ environ.get('SHERPA_ROOT_DIR') }}"

build:
  number: 0
  string: cpu_py{{ environ.get('SHERPA_PYTHON_VERSION') }}_torch{{ environ.get('SHERPA_TORCH_VERSION') }}
  script: |
    python setup.py install --single-version-externally-managed --record=record.txt
    COPY build/lib.win-amd64-*/sherpa/bin/sherpa.exe %PREFIX%\Library\bin || exit 1
    COPY build/lib.win-amd64-*/sherpa/lib/sherpa_core.lib %PREFIX%\Library\lib || exit 1

  features:
    - cpuonly # [not osx]

requirements:
  build:
    - {{ compiler('c') }} # [win]
    - {{ compiler('cxx') }} # [win]

  host:
    - anaconda-client
    - cmake=3.18
    - python
    - pytorch={{ environ.get('SHERPA_TORCH_VERSION') }}
    - kaldifeat
    - kaldi_native_io
    - k2
    - cpuonly
    - gcc_linux-64=7 # [linux]

  run:
    - python
    - pytorch={{ environ.get('SHERPA_TORCH_VERSION') }}
    - kaldifeat
    - kaldi_native_io
    - k2

about:
  home: https://github.com/k2-fsa/sherpa
  license: Apache V2
  license_file: LICENSE
  summary: Streaming and non-streaming ASR server for next-gen Kaldi
  description: |
    An ASR server framework supporting both streaming and non-streaming
    recognition using next-gen Kaldi.
