name: build_conda_cpu

on:
  push:
    branches:
    - master
    - t2
    tags:
      - '*'

jobs:
  build_conda_cpu:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-18.04, macos-10.15, windows-2019]
        os: [macos-10.15]
        # python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        python-version: ["3.8"]
        torch: ["1.12.0"]

    steps:
      # refer to https://github.com/actions/checkout
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: sherpa

      - name: Install conda dependencies
        shell: bash -l {0}
        run: |
          conda install -y -q anaconda-client
          conda install -y -q conda-build
          conda install -y -q -c pytorch pytorch=${{ matrix.torch }} cpuonly

      - name: Display Python version
        shell: bash -l {0}
        run: |
          python -c "import sys; print(sys.version)"
          which python

      - name: Display conda info
        shell: bash -l {0}
        run: |
          conda env list
          conda info
          which conda
          python --version
          which python
          python -m torch.utils.collect_env

      - name: Build sherpa
        shell: bash -l {0}
        env:
          SHERPA_PYTHON_VERSION: ${{ matrix.python-version}}
          SHERPA_TORCH_VERSION: ${{ matrix.torch }}
          SHERPA_CONDA_TOKEN: ${{ secrets.SHERPA_CONDA_TOKEN}}
        run: |
          ./scripts/build_conda_cpu.sh

      - name: Display generated files
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          ls -lh /usr/share/miniconda/envs/sherpa/conda-bld/linux-64

      - name: Upload generated files
        if: startsWith(matrix.os, 'ubuntu')
        uses: actions/upload-artifact@v2
        with:
          name: cpu-torch-${{ matrix.torch }}-python-${{ matrix.python-version }}-${{ matrix.os }}
          path: /usr/share/miniconda/envs/sherpa/conda-bld/linux-64/*.tar.bz2

      - name: Display generated files
        if: startsWith(matrix.os, 'windows')
        shell: bash -l {0}
        run: |
          ls -lh /c/Miniconda/envs/sherpa/conda-bld
          ls -lh /c/Miniconda/envs/sherpa/conda-bld/*/*
          ls -lh /c/Miniconda/envs/sherpa/conda-bld/win-64/*

      - name: Upload generated files
        if: startsWith(matrix.os, 'windows')
        uses: actions/upload-artifact@v2
        with:
          name: cpu-torch-${{ matrix.torch }}-python-${{ matrix.python-version }}-${{ matrix.os }}
          path: c:/Miniconda/envs/sherpa/conda-bld/win-64/*.tar.bz2

      - name: Display generated files
        if: startsWith(matrix.os, 'macos')
        run: |
          ls -lh /usr/local/miniconda/envs/sherpa/conda-bld/osx-64

      - name: Upload generated files
        if: startsWith(matrix.os, 'macos')
        uses: actions/upload-artifact@v2
        with:
          name: cpu-torch-${{ matrix.torch }}-python-${{ matrix.python-version }}-${{ matrix.os }}
          path: /usr/local/miniconda/envs/sherpa/conda-bld/osx-64/*.tar.bz2
